FROM python:3.10

RUN apt-get update && \
    apt-get install -y optipng && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /db-interact

# Copy Python app code
COPY . /db-interact

RUN pip install --no-cache-dir -r requirements.txt

# Expose required ports
# EXPOSE 8080

# Command to run pipeline
# CMD ["python", "db-interact.py"]
