FROM python:3.10

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk optipng xsltproc fop && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME environment variable for Java
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

WORKDIR /snakefarm-server

# Copy Python app code
COPY . /snakefarm-server

RUN pip install --no-cache-dir -r requirements.txt

# Expose required ports
# EXPOSE 8080

# Command to start server
# CMD ["python", "snakefarm-server.py"]